services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  nginx-proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  idp:
    container_name: idp
    image: node:18-alpine
    restart: always
    working_dir: /home/app/apps/idp
    volumes:
      - .:/home/app
    ports:
      - ${IDP_SERVER_PORT}:80
    environment:
      - VIRTUAL_HOST=${IDP_VIRTUAL_HOST}
    command: "yarn local"

  client:
    container_name: client
    image: node:18-alpine
    restart: always
    working_dir: /home/app/apps/client
    volumes:
      - .:/home/app
    ports:
      - ${CLIENT_SERVER_PORT}:80
    environment:
      - VIRTUAL_HOST=${CLIENT_VIRTUAL_HOST}
    command: "yarn local"